#----------------------------------------------------------------------
# This file was generated by E:/py_code/deal_file/evernote/utils/encode_bitmap_util.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

empty_note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAACt0lEQVR4Xu2bsZLTMBCGdzN5'
    b'CAoKao4mlhu64wGYayDdUfIadzwGlJTkIcgNNBm8TgUtFAzMvUSWUca+sX1JrJXRybLkJpOJ'
    b'drX7SfpXckYIkT8Yef7QApDn+SUzvwSA5wDwOBA4f5i5KMvywibeOwBKqU8A8NrGyVhsiEg8'
    b'o/cGSqlCf4wlkSFxSCFglmVvEfH9kE7HZiuBoAF8RMTLOglmfjebzdZFUazHllgzHqUU6+86'
    b'XkS86sZqCgGVUj8B4EntYLfbnW232x9jTr5atnsAOtEsy65tIWgAe0f1Y0rON6A67jpeWwiT'
    b'AaAHxAbCpADYQJgcACmEXgDVtHoFAGeW637NzDdlWV5b2h8062pAt5HpcugFoJT6DADnA4P/'
    b'TkTPBvpomfcBqGbCFSLeA98UehMArSphm0S3ugjBronoRWcfsC/f8/n80WazuT0WV5ZlJyEE'
    b'C6CxgVsS0erUwJyCIAZguk9wvb9obuFNYjoCYRUsgGo3eHeIQ8QLZv5GRH8Fy+E2aAAVhEHH'
    b'+OABaAhDXuR4AzC0CthWo642JQB9at33+7GRsLWzHVlTu9HMANOA/3e7wQBsAzKp1ba+JXYJ'
    b'QOcFkIkIOjkMCauAZJCbbQ+dIVpnm14Aro7DwQCwRT9WO7EGjDUR27gSAKkI2pIeq514BjyQ'
    b'WLniNbwKRA/A1dD48iteAr4CddVvApCqQPvP4N6tcPQiGD0AV2Lky28SwSSCQhH0NVVd9Ste'
    b'AtGLYPQAXE1FX37FS8BXoK76TQBSGRSWwehFMHoArsTIl98kgkkEhSLoa6q66vfQEgjywoQN'
    b'oDzPz5lZ/9tdP7+DvTIjBbBYLJ4i4rJzs2Q1yUtTpnAQ8c3krs2ZJg8AKyJaTuripCB5IqJc'
    b't5/C1VnTvH8x8xcA+FqW5YfaSHzV1LS3UNpFD+Af3Clwa2P/uxAAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
more = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAoElEQVQ4T+3ToQ6BYRSH8Z8u'
    b'qSTTXIFLICjmCkwRVM2+aKqRdJsZQXAHFFE0ySTJFdi3nY/uq0583nOed/vvnIKcVcg57y/w'
    b'yaCGJs44RbClYM9gr+BpXzHYPQtxiV40tHDAAPNgU4zQwDHYHu1McEE9HoaYxXAqSWuLDrpY'
    b'B3ugnAkS9OPnCa6pHWPcsMMKFSxQxQbJfw++e/DzTeUO8Q06OhsRiMwehAAAAABJRU5ErkJg'
    b'gg==')

#----------------------------------------------------------------------
sort = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAjklEQVQ4T2NkoBAwUqifAWyA'
    b'goKGAiML43xSDPv/53/igwc3HlDHAFJsRldLUhgoqGg4PLhz4wCyISQZoKSi+f8fw39HZEOI'
    b'CoP7d647gmylnQHEBiJOF9DVgP8MjGGMDP9XwQKT5EAEuZaRgWH13TvXw6BswkkZKRbOMDIw'
    b'3INphhtAbBhgU0dSQsJmAADz51sRDXokhAAAAABJRU5ErkJggg==')

